refactor scripting-list job

diff --git a/jobs/scripting-list/templates/post-deploy.erb b/jobs/scripting-list/templates/post-deploy.erb
--- a/jobs/scripting-list/templates/post-deploy.erb
+++ b/jobs/scripting-list/templates/post-deploy.erb
@@ -1,18 +1,25 @@
 #!/bin/bash
+set -e # Exit immediately if a simple command exits with a non-zero status
+set -u # Report the usage of uninitialized variables
 
-set -e # exit immediately if a simple command exits with a non-zero status
-set -u # report the usage of uninitialized variables
+#--- Initialize context
+> /var/vcap/sys/log/scripting/post-deploy.stderr.log
+> /var/vcap/sys/log/scripting/post-deploy.stdout.log
+echo "$(date -u "+%Y-%m-%d %H:%M:%S") => Begin post-deploy"
 
+#--- Generate script list to run
+<% i = 0 %>
 <% if_p('scripting-list.post-deploy-scripts') do |value| %>
 <% p('scripting-list.post-deploy-scripts').each do |script| %>
-## script list item:
+<% i = i + 1 %>
+
+cat > /var/vcap/data/scripting-list/post-deploy-<%= i %>.sh <<'SCRIPTING_EOF'
 <%= script %>
-## ---------------
+SCRIPTING_EOF
+
+. /var/vcap/data/scripting-list/post-deploy-<%= i %>.sh
 <% end %>
 <% end %>
 
-
-EXITSTATUS=0
-
-echo "post deploy list is complete; exit status $EXITSTATUS"
-exit $EXITSTATUS
+echo "$(date -u "+%Y-%m-%d %H:%M:%S") => End post-deploy"
+exit 0
diff --git a/jobs/scripting-list/templates/post-start.erb b/jobs/scripting-list/templates/post-start.erb
--- a/jobs/scripting-list/templates/post-start.erb
+++ b/jobs/scripting-list/templates/post-start.erb
@@ -1,19 +1,25 @@
 #!/bin/bash
+set -e # Exit immediately if a simple command exits with a non-zero status
+set -u # Report the usage of uninitialized variables
 
-set -e # exit immediately if a simple command exits with a non-zero status
-set -u # report the usage of uninitialized variables
+#--- Initialize context
+> /var/vcap/sys/log/scripting/post-start.stderr.log
+> /var/vcap/sys/log/scripting/post-start.stdout.log
+echo "$(date -u "+%Y-%m-%d %H:%M:%S") => Begin post-start"
 
-
+#--- Generate/run scripts from list
 <% i = 0 %>
 <% if_p('scripting-list.post-start-scripts') do |value| %>
 <% p('scripting-list.post-start-scripts').each do |script| %>
 <% i = i + 1 %>
-echo '<%= script %>' >> /var/vcap/data/scripting-list/shell-<%= i %>.sh
-. /var/vcap/data/scripting-list/shell-<%= i %>.sh
+
+cat > /var/vcap/data/scripting-list/post-start-<%= i %>.sh <<'SCRIPTING_EOF'
+<%= script %>
+SCRIPTING_EOF
+
+. /var/vcap/data/scripting-list/post-start-<%= i %>.sh
 <% end %>
 <% end %>
 
-EXITSTATUS=0
-
-echo " post-start list is complete; exit status $EXITSTATUS"
-exit $EXITSTATUS
+echo "$(date -u "+%Y-%m-%d %H:%M:%S") => End post-start"
+exit 0
diff --git a/jobs/scripting-list/templates/post-stop.erb b/jobs/scripting-list/templates/post-stop.erb
--- a/jobs/scripting-list/templates/post-stop.erb
+++ b/jobs/scripting-list/templates/post-stop.erb
@@ -1,18 +1,25 @@
 #!/bin/bash
+set -e # Exit immediately if a simple command exits with a non-zero status
+set -u # Report the usage of uninitialized variables
 
-set -u # report the usage of uninitialized variables
+#--- Initialize context
+> /var/vcap/sys/log/scripting/post-stop.stderr.log
+> /var/vcap/sys/log/scripting/post-stop.stdout.log
+echo "$(date -u "+%Y-%m-%d %H:%M:%S") => Begin post-stop"
 
+#--- Generate script list to run
+<% i = 0 %>
 <% if_p('scripting-list.post-stop-scripts') do |value| %>
 <% p('scripting-list.post-stop-scripts').each do |script| %>
-## script list item:
+<% i = i + 1 %>
+
+cat > /var/vcap/data/scripting-list/post-stop-<%= i %>.sh <<'SCRIPTING_EOF'
 <%= script %>
-## ---------------
+SCRIPTING_EOF
+
+. /var/vcap/data/scripting-list/post-stop-<%= i %>.sh
 <% end %>
 <% end %>
 
-
-
-EXITSTATUS=0
-
-echo " post-stop list is complete; exit status $EXITSTATUS"
-exit $EXITSTATUS
+echo "$(date -u "+%Y-%m-%d %H:%M:%S") => End post-stop"
+exit 0
diff --git a/jobs/scripting-list/templates/pre-start.erb b/jobs/scripting-list/templates/pre-start.erb
--- a/jobs/scripting-list/templates/pre-start.erb
+++ b/jobs/scripting-list/templates/pre-start.erb
@@ -1,20 +1,25 @@
 #!/bin/bash
+set -e # Exit immediately if a simple command exits with a non-zero status
+set -u # Report the usage of uninitialized variables
 
-set -e # exit immediately if a simple command exits with a non-zero status
-set -u # report the usage of uninitialized variables
+#--- Initialize context
+> /var/vcap/sys/log/scripting/pre-start.stderr.log
+> /var/vcap/sys/log/scripting/pre-start.stdout.log
+echo "$(date -u "+%Y-%m-%d %H:%M:%S") => Begin pre-start"
 
+#--- Generate script list to run
+<% i = 0 %>
 <% if_p('scripting-list.pre-start-scripts') do |value| %>
 <% p('scripting-list.pre-start-scripts').each do |script| %>
-## script list item:
+<% i = i + 1 %>
+
+cat > /var/vcap/data/scripting-list/pre-start-<%= i %>.sh <<'SCRIPTING_EOF'
 <%= script %>
-## ---------------
+SCRIPTING_EOF
+
+. /var/vcap/data/scripting-list/pre-start-<%= i %>.sh
 <% end %>
 <% end %>
 
-
-
-
-EXITSTATUS=0
-
-echo " pre-start list is complete; exit status $EXITSTATUS"
-exit $EXITSTATUS
+echo "$(date -u "+%Y-%m-%d %H:%M:%S") => End pre-start"
+exit 0
diff --git a/jobs/scripting-list/templates/pre-stop.erb b/jobs/scripting-list/templates/pre-stop.erb
--- a/jobs/scripting-list/templates/pre-stop.erb
+++ b/jobs/scripting-list/templates/pre-stop.erb
@@ -1,19 +1,25 @@
 #!/bin/bash
+set -e # Exit immediately if a simple command exits with a non-zero status
+set -u # Report the usage of uninitialized variables
 
-set -u # report the usage of uninitialized variables
+#--- Initialize context
+> /var/vcap/sys/log/scripting/pre-stop.stderr.log
+> /var/vcap/sys/log/scripting/pre-stop.stdout.log
+echo "$(date -u "+%Y-%m-%d %H:%M:%S") => Begin pre-stop"
 
+#--- Generate script list to run
+<% i = 0 %>
 <% if_p('scripting-list.pre-stop-scripts') do |value| %>
 <% p('scripting-list.pre-stop-scripts').each do |script| %>
-## script list item:
+<% i = i + 1 %>
+
+cat > /var/vcap/data/scripting-list/pre-stop-<%= i %>.sh <<'SCRIPTING_EOF'
 <%= script %>
-## ---------------
+SCRIPTING_EOF
+
+. /var/vcap/data/scripting-list/pre-stop-<%= i %>.sh
 <% end %>
 <% end %>
 
-
-
-
-EXITSTATUS=0
-
-echo " pre-stop is complete; exit status $EXITSTATUS"
-exit $EXITSTATUS
+echo "$(date -u "+%Y-%m-%d %H:%M:%S") => End pre-stop"
+exit 0
